### ISSUE TITLE
Extra venue for the homescreen and ETHSamba Hack

### ISSUE THREAD

**Issue by xdaluca** [PWNFinance/gm_ethrio#14]
Would it be possible to add this venue? It will be a satellite venue for the ETHSamba Hack event.

Casa Bamba is already live on the homepage and will be the main venue.

Hacker House will be for the hackathon and open 24 hours after the hackathon starts.

**Name:** 
ETHSamba Hacker House
**Address:**
R. Aprazível, 5 - Santa Teresa, Rio de Janeiro - RJ, 20241-270
**Description:** 
We will have our own Hacker House that will be open 24 hours from the start of the Hackathon. In it, all you need to build your best project and take quick breaks by jumping in the pool or admiring the view!

**Link:** 
https://www.google.com/maps/place/R.+Apraz%C3%ADvel,+5+-+Santa+Teresa,+Rio+de+Janeiro+-+RJ,+20241-270/@-22.9221703,-43.1895941,17z/data=!3m1!4b1!4m6!3m5!1s0x997f9d87e34301:0xc7620d4c57ce27f7!8m2!3d-22.9221753!4d-43.1874001!16s%2Fg%2F11c43t0fy4

**Photo:**
![front](https://user-images.githubusercontent.com/80516439/227269156-8e83b60a-fe6f-4a4f-892e-3698e9e83f6c.jpeg)

**Comment by petulii** [comment]
Added the venue.
